language: php
php:
  - '7.1'
  - '7.2'

before_install:
  - mkdir -p app/etc var
  - echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json
  - if [ -n "$GITHUB_TOKEN" ]; then composer config github-oauth.github.com ${GITHUB_TOKEN}; fi;

install:
  - composer install --prefer-dist

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

script:
  - ./vendor/bin/phpcs --config-set installed_paths vendor/magento/marketplace-eqp/,vendor/smile/magento2-smilelab-phpcs/phpcs-standards/
  - ./vendor/bin/phpqa --ignoredDirs vendor,build --output cli --ansi  --tools phpcs:0,phpmd:0,phpcpd:0,parallel-lint:0,phpmetrics,phploc,pdepend
